{% set name = "vertica-python" %}
{% set version = "0.7.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "67b7cf6c684ebf3b152947cc80b1e16743d8454ae5fec052420eef343e7a3617" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - python-dateutil >=1.5
    - pytz
    - future
    - six >=1.10.0
    - psycopg2 >=2.5.1

test:
  imports:
    - vertica_python
    - vertica_python.tests
    - vertica_python.vertica
    - vertica_python.vertica.messages
    - vertica_python.vertica.messages.backend_messages
    - vertica_python.vertica.messages.frontend_messages

about:
  home: https://github.com/uber/vertica-python/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A native Python client for the Vertica database.
  dev_url: https://github.com/uber/vertica-python/

extra:
  recipe-maintainers:
    - pmlandwehr
