{%set name = "vertica-python" %}
{%set version = "0.6.13" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f809821a8780cdb02a61d56e646fd73e71ab3f7a89ba9511a50390a025cdbaf0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    - setup.patch # remove unused import ordereddict

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - python-dateutil >=1.5
    - pytz
    - future
    - psycopg2 >=2.5.1

test:
  imports:
    - vertica_python
    - vertica_python.tests
    - vertica_python.vertica
    - vertica_python.vertica.messages
    - vertica_python.vertica.messages.backend_messages
    - vertica_python.vertica.messages.frontend_messages

about:
  home: https://github.com/uber/vertica-python/
  license: MIT
  license_file: LICENSE
  summary: 'A native Python client for the Vertica database.'

extra:
  recipe-maintainers:
    - pmlandwehr
