travis:
  secure:
    BINSTAR_TOKEN: NoTvdPoVbFHeToJnWCZOH2FAft0LgI09YyZpX9+/RBK7V5mKPImbNr4NZAA4nK6Tmj1DizCEVIwCvYxVdcWhaTH+upYhhHVQwL7jbnhJIy1Xh1t1mmN5PWDCIzdWTPhvJCCcdJneAqmOG2ZJOJwaBtG9ntXjl1fCdI96Kn5qjmQZ11Nk3RZ1Zf9h98CeYFKPC4fmMTtTqfiwdIIJ01/XF7F1TATb23prQz6qBQsOvDLKTNSpbOgoP2aOsuXeIJSazy7kGfkwn/mJxkkiTXKbY6fYClvZ0zKdwcVK3Gzi1OA2yYeuK3l1YQ79sFL3uiUItIkoAJ1sV8xB7yd4AO+3n7thSRuTiavrxzeogvMopMZ/xJNkQz4kOY2/T/s4gfRrQfVDI3vceOv9YIkC/jxpkpJDtbwEkvmAS1GpEtg7Sn/ofzHcm+knXclHkRk52Zb+dU0PWjYEwkIqKzBnrHq+ROjK10ZvR1Z9qsbwdPkSuAtP0bxdayzksPPotfaws9XUTlBtKtbeEu1DsKxfFl+BxgmlSMQZgzVVzNm/d+F/Am+A8P2g953MLRHkY3fGtzVBEeA2+BjmLNFRLwjDGE9sr/2Y9bq369Qk0AXpWCv+1BjNEPrO1Bi8WejdV7rfm4NAu5FeocSANXJYK5miHtI1ndkn6H9jSpVjaSunVYOKJw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
