travis:
  secure:
    BINSTAR_TOKEN: PEzuFPBIG884EPODrG/a5ORRBJyOWbTZKkqDlJlewPusxkv0kprSRNbqppWcBiKOMzKuGkFvBFgu5g9a93/pIqyyU/QC8s7I8B1aXYcak1hzY9QMrGQRhpS8suzhILT7gUnGmchPYDM/BoCy6ObJAyAYUABk7fE2YmdunZE0XT9iq+wL9aEPRTpzr/pyQ3dscjnRMAkswqGj7YyNIcfnozIawSCzI5EuS7dTJAs8YJ+9FwOQ0+RSSSXtf419rpuBnrjCeCJuTVxFr2VgsZeaQAMdwpzJVl41M2kzUAGtfYAy7Fr/DrznUh4vM1+BAPYsSEnzIJk7iBPAiao09YoFEuCwgIQWdHqRmml/PkZ+6IGXfLmc+butt5QIZ/B+toJe/jAWmdCtXzDenxnLcDIn1Iy/UCaQtV43HQnnYkn9bTepWqdYxhbNdgqZsv1R4Ff2BiXqRFcqtCIWY8lIE8dsJdpYokPgj/NY65zoSBKqkMeT67ebbrTLL63ST2zkgOAs28dNs6YY84YDPHmsNLqIlBstFBUEqRzqw4WKxRGwv4hAhTG0cWY8hQasepzuM6NFuZwWp1VKm+qrqU522r07T3AJCoHFtQW9jKKOUbi1wzS+LXfxCrNmC45KmsAlb4kKltJ/ESY0wOCprKTnc41Ixdb7mwtisf/SFr/z8VuTcCU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
